export const data = [
  {
    id: 1,
    name: 'Light pinl Shirt',
    title: 'Nike T-shirt',
    category: 'Clothing',
    image: '/images/img.jpg',
    countInStock: '4',
    price: 35,
    brand: 'Nike',
    rating: '4.5',
    numReviews: 10,
    description: 'original T-shirt',
  },
  {
    id: 2,
    name: 'Nike Black sneakers',
    title: 'Nike Sneakers',
    category: 'Foot wears',
    image: '/images/img.jpg',
    countInStock: '12',
    price: 90,
    brand: 'Nike',
    rating: '4.1',
    numReviews: 20,
    description: 'original Sneakers',
  },
  {
    id: 3,
    name: 'Nike White sneakers',
    title: 'Nike Sneakers',
    category: 'FootWear',
    image: '/images/img03.jpg',
    countInStock: '25',
    price: 100,
    brand: 'Nike',
    rating: '4.9',
    numReviews: 10,
    description: 'original Sneakers',
  },
  {
    id: 4,
    name: 'Nike Fancy sneakers',
    title: 'Nike Sneakers',
    category: 'FootWear',
    image: '/images/img04.jpg',
    countInStock: '2',
    price: 150,
    brand: 'Nike',
    rating: '4.7',
    numReviews: 27,
    description: 'original Sneakers',
  },
  {
    id: 5,
    name: 'Nike Fancy sneakers',
    title: 'Nike Sneakers',
    category: 'FootWear',
    image: '/images/img04.jpg',
    countInStock: '2',
    price: 150,
    brand: 'Nike',
    rating: '4.7',
    numReviews: 27,
    description: 'original Sneakers',
  },
];
