export const data = [
  {
    name: 'Light pinl Shirt',
    title: 'Nike T-shirt',
    category: 'Clothing',
    image: '/images/img.jpg',
    countInStock: 4,
    price: 35,
    brand: 'Nike',
    rating: 4.5,
    numReviews: 10,
    description: 'original T-shirt',
  },
  {
    name: 'Nike Black sneakers',
    title: 'Nike Sneakers',
    category: 'Foot wears',
    image: '/images/img.jpg',
    countInStock: 12,
    price: 90,
    brand: 'Nike',
    rating: 4.1,
    numReviews: 20,
    description: 'original Sneakers',
  },
  {
    name: 'Addidas White sneakers',
    title: 'Addidas Sneakers',
    category: 'FootWear',
    image: '/images/img03.jpg',
    countInStock: 25,
    price: 100,
    brand: 'Nike',
    rating: 4.9,
    numReviews: 10,
    description: 'original Sneakers',
  },
  {
    name: 'Fancy Cake',
    title: 'Cream Cake',
    category: ['cake'],
    image: '/images/img04.jpg',
    countInStock: 2,
    price: 150,
    brand: 'Nike',
    rating: 4.7,
    numReviews: 27,
    description: 'original Sneakers',
  },
  {
    name: 'Pink Cake',
    title: 'Chocolate Cake',
    category: ['Cake'],
    image: '/images/img04.jpg',
    countInStock: 2,
    price: 150,
    brand: 'Nike',
    rating: 4.7,
    numReviews: 27,
    description: 'original Sneakers',
  },
];
